name: Intelligent Issue Triage

# Trigger this workflow when a new issue is opened or edited.
on:
  issues:
    types: [opened, edited]

# This job will analyze the issue and apply labels.
jobs:
  analyze-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write # This permission is required to add labels to the issue.

    steps:
      - name: Use Gemini CLI to Triage Issue
        # We use a specific action for the Gemini CLI.
        uses: google/gemini-cli@v1
        with:
          # This specifies the command to run.
          command: issue triage
          # We pass the issue number to the CLI so it knows which issue to analyze.
          issue_number: ${{ github.event.issue.number }}
          # This provides the GitHub token, allowing the action to add labels.
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # This is the API key for the Gemini model. You must add this as a secret.
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}

      - name: Print Triage Results
        # This step is for demonstration; it prints the output from the previous step.
        run: |
          echo "Issue triage complete."
